### PR TITLE
Allow ResourcePrototype methods in fake ClientBundle

### PR DESCRIPTION
**Pull request by zbynek**
This PR allows you to mock ResourcePrototypes that have a method producing another ResourcePrototype (usecase: SVGResource that can produce SVGs in different colors)

### CODE REVIEW

**Comment by zbynek** [comment]
I signed it!

**Comment by ekuefler** [comment]
Thanks! Is it possible to add a test for this like in https://github.com/google/gwtmockito/blob/master/gwtmockito/src/test/java/com/google/gwtmockito/GwtMockitoTest.java#L384?

**Comment by zbynek** [comment]
@ekuefler thanks for checking, I added a test.

**Comment by ekuefler** [comment]
Thank you!

**Comment by zbynek** [comment]
@ekuefler do you have any plans for the next release?

**Comment by ekuefler** [comment]
I've pushed a new snapshot release at https://oss.sonatype.org/content/repositories/snapshots/com/google/gwt/gwtmockito/gwtmockito/1.1.9-SNAPSHOT/. Could you try that out to confirm it's working as expected? If so, there are a couple more things I need to verify, then I'll plan on doing a full release of 1.1.9 in a week or two.

**Comment by zbynek** [comment]
Sorry for the delay. I can confirm the fix works with 1.1.9-SNAPSHOT.

FYI: there is (unrelated?) IllegalAccessError when protected nested interface
https://github.com/geogebra/geogebra/blob/3bfd6e55d130793c5420151fdfe768b063878f3a/common/src/main/java/org/geogebra/common/io/MyXMLio.java#L472
is implemented in a nested subclass
https://github.com/geogebra/geogebra/blob/master/web/src/main/java/org/geogebra/web/html5/io/MyXMLioW.java#L50

```
java.lang.IllegalAccessError: class org.geogebra.web.html5.io.MyXMLioW$XMLStreamStringW cannot access its superinterface org.geogebra.common.io.MyXMLio$XMLStream
```
I guess this kind of nesting is not a common usecase and there are easy ways to avoid it (e.g. make the interface public), so not a problem a for me.

**Pull request merged**
